import sharp from "sharp";
import potrace from "potrace";
import { promisify } from "util";

const potraceTrace = promisify(potrace.trace);

/**
 * Converts an image to a black-and-white bitmap and vectorizes it using Potrace
 * @param {Buffer} imageBuffer - The uploaded image buffer
 * @returns {Promise<string>} - SVG string generated by Potrace
 */
export async function vectorizeImage(imageBuffer) {
  try {
    // Step 1: Process image with Sharp
    // Resize to 500px width while maintaining aspect ratio
    // Convert to grayscale and apply threshold for black/white
    const processedBuffer = await sharp(imageBuffer)
      .resize(500, null, {
        fit: "inside",
        withoutEnlargement: false,
      })
      .greyscale()
      .normalise()
      .threshold(128) // Convert to pure black and white
      .toBuffer();

    // Step 2: Vectorize with Potrace
    const svg = await potraceTrace(processedBuffer, {
      turnPolicy: potrace.Potrace.TURNPOLICY_MINORITY,
      turdSize: 2,
      optCurve: true,
      alphaMax: 1,
      optTolerance: 0.2,
      threshold: 128,
      blackOnWhite: true,
      color: "black",
      background: "transparent",
    });

    return svg;
  } catch (error) {
    console.error("Error in vectorizeImage:", error);
    throw new Error(`Failed to vectorize image: ${error.message}`);
  }
}
